apiVersion: v1
kind: Service
metadata:
  name: private-fastapi-demo-service
  namespace: private-demo-dev
spec:
  type: LoadBalancer
  selector:
    app: private-fastapi-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
