apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-fastapi-demo
  namespace: private-demo-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: private-fastapi-demo
  template:
    metadata:
      labels:
        app: private-fastapi-demo
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: private-fastapi-demo
          image: abdullahmasoodx/private-fastapi-argo-demo:initial
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "staging"
            - name: APP_VERSION
              value: "initial"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
